export const movies = [
  { id: 1, name: "Inception", genre: "Sci-Fi", rating: 4.8 },
  { id: 2, name: "The Shawshank Redemption", genre: "Drama", rating: 4.7 },
  { id: 3, name: "The Dark Knight", genre: "Action", rating: 4.9 },
  { id: 4, name: "Pulp Fiction", genre: "Crime", rating: 4.5 },
  { id: 5, name: "Forrest Gump", genre: "Drama", rating: 4.6 },
  { id: 6, name: "The Matrix", genre: "Action", rating: 4.8 },
  { id: 7, name: "The Godfather", genre: "Crime", rating: 4.9 },
  { id: 8, name: "Titanic", genre: "Romance", rating: 4.3 },
  { id: 9, name: "Avatar", genre: "Adventure", rating: 4.7 },
  { id: 10, name: "Gladiator", genre: "Action", rating: 4.5 },
  { id: 11, name: "The Lion King", genre: "Animation", rating: 4.6 },
  { id: 12, name: "Inglourious Basterds", genre: "War", rating: 4.4 },
  { id: 13, name: "The Silence of the Lambs", genre: "Thriller", rating: 4.9 },
  { id: 14, name: "The Social Network", genre: "Biography", rating: 4.5 },
  { id: 15, name: "Jurassic Park", genre: "Adventure", rating: 4.7 },
  { id: 16, name: "Interstellar", genre: "Sci-Fi", rating: 4.8 },
  { id: 17, name: "The Departed", genre: "Crime", rating: 4.6 },
  { id: 18, name: "Fight Club", genre: "Drama", rating: 4.7 },
  { id: 19, name: "Casablanca", genre: "Romance", rating: 4.8 },
  { id: 20, name: "Eternal Sunshine", genre: "Romance", rating: 4.5 },
];
